### ISSUE TITLE
Adding vanilla command (gamemode) [Error running command]

### ISSUE THREAD

**Issue by gevalo1** [cnaude/PurpleIRC-spigot#3] opened 2015-03-07 14:17 UTC
When I add the gamemode command from the samplebot.yml, and try to execute it from irc, I get the following error in console: 

ERROR Error running command: Unhandled exception executing 'gamemode 0 gevalo1' in org.bukkit.craftbukkit.v1_8_R1.command.VanillaCommandWrapper(gamemode)

my botconfig is as follows: http://pastebin.com/BZck23b5

**Comment by cnaude** [comment] 2015-03-07 14:37
What version of PurpleIRC and Spigot is this?

**Comment by gevalo1** [comment] 2015-03-07 14:47
Spigot: This server is running CraftBukkit version git-Spigot-8a983f9-e81edfc (MC: 1.8) (Implementing API version 1.8-R0.1-SNAPSHOT)

PurpleIRC: 1.0-44

**Comment by cnaude** [comment] 2015-03-07 15:08
Would you mind trying the very latest Spigot build?
I am unable to reproduce the error with git-Spigot-c3c767f-33d5de3.

**Comment by gevalo1** [comment] 2015-03-11 19:27
Sorry for the long delay, but since I can't just easily use any spigot build because of my server provider, I couldn't test it on the one you suggested.

Today we did update to: This server is running CraftBukkit version git-Spigot-26dfd01-ad2f806 (MC: 1.8.3) (Implementing API version 1.8.3-R0.1-SNAPSHOT)
But this did not solve the problem.

**Comment by cnaude** [comment] 2015-03-11 20:14
What other plugins are you running?

**Comment by gevalo1** [comment] 2015-03-11 20:38
Plugins (21): LagMeter, PvPControl, WorldEdit, NickNames, HawkEye, CommandBook, OpenInv, ScheduledAnnouncer2, HealthBar, Modifyworld, PermissionsEx, FirstJoinPlus, LogBlock, AutoSaveWorld, WorldGuard, MCBans, PermissionsExTabColors, dynmap, Statistics, PurpleIRC, ChatEx (there is a reason for having both logblock and hawkeye atm)

**Comment by cnaude** [comment] 2015-03-11 20:43
Can you enable debug mode and send the command and then pastebin the debug output? To turn on debug mode do "/irc debug t" and to turn off do "/irc debug f"

**Comment by gevalo1** [comment] 2015-03-11 20:49
Here it is: I noticed it says that gamemode is a commandbook command... might have something to do with it....

http://pastebin.com/YjAEyCmM

**Comment by cnaude** [comment] 2015-03-11 20:52
That's exactly what I was looking for. CommandBook does some weird things with commands.

**Comment by gevalo1** [comment] 2015-03-12 14:44
I fixed the error by changing:
'game_command: gamemode %ARGS%' to 'game_command: minecraft:gamemode %ARGS%'

But now whenever I do the command, the bot sends me a private msg on irc:
'Command sent: minecraft:gamemode 0 gevalo1'

I checked if it was a config option, but  couldn't really find anything. I thought it might have been the command notify option; but this is set to false:

command-notify:
  enabled: false

Note: I do not get any PM's when trying other commands.

So... ?

**Comment by cnaude** [comment] 2015-03-12 15:50
The reason you get the notification is because it is dispatching a vanilla command. The Spigot API does not provide any method of returning the results of a vanilla command. Thus PurpleIRC will notify you that the command was successfully sent. There is not an option to disable that feature. I can make it optional if you would like it disabled.

**Comment by gevalo1** [comment] 2015-03-12 15:52
If you want to, yes please.. Would be very helpful.

**Comment by cnaude** [comment] 2019-11-18 05:33
Closing very old tickets. Let me know if this is still an issue.

**Closed as completed by cnaude** 2019-11-18 05:33 UTC
